---
- name: add apt repository
  apt_repository: repo=ppa:webupd8team/java

- name: configure debconf
  debconf: name=oracle-java{{ oracle_java_version }}-installer question=shared/accepted-oracle-license-v1-1 value="true" vtype="select"

- name: install
  apt: name={{ item }} update_cache=yes
  with_items:
    - oracle-java{{ oracle_java_version }}-installer
    - oracle-java{{ oracle_java_version }}-unlimited-jce-policy
    - oracle-java{{ oracle_java_version }}-set-default
