---
- name: create deployment directory
  file: path=/opt state=directory mode=755

- name: fetch binary package
  get_url: url={{ url }} dest=/opt/{{ package }}

#- name: clean obsolete binary packages

- name: install binary package
  unarchive: src=/opt/{{ package }} creates=/opt/{{ package | basename }} dest=/opt copy=no

- name: create symlink to installation directory
  file: path="{{ dest }}" src=/opt/{{ package | basename }} state=link

#- name: clean obsolete installation
