---
- name: setup group
  group: name=kafka system=yes

- name: setup user
  user: name=kafka system=yes group=kafka

- name: create upstart config
  template: dest=/etc/init/kafka.conf src=upstart.conf.j2
  notify:
    - restart kafka

- name: fetch binary package
  get_url: dest=/root/kafka_{{kafka_scala_version}}-{{kafka_version}}.tgz url="http://apache.mirrors.tds.net/kafka/{{kafka_version}}/kafka_{{kafka_scala_version}}-{{kafka_version}}.tgz"

- name: uncompress binary package
  unarchive: copy=no creates=/opt/kafka_{{kafka_scala_version}}-{{kafka_version}} dest=/opt src=/root/kafka_{{kafka_scala_version}}-{{kafka_version}}.tgz

- name: create symlink to installation directory
  file: path=/opt/kafka state=link src=/opt/kafka_{{kafka_scala_version}}-{{kafka_version}}

- name: create symlink to conf directory
  file: path={{kafka_conf_dir}} state=link src=/opt/kafka/config

- name: create data directory
  file: path={{kafka_data_dir}} state=directory owner=kafka group=kafka mode=755

- name: create log directory
  file: path={{kafka_log_dir}} state=directory owner=kafka group=kafka mode=755

- name: Setup server.properties
  template: dest="{{kafka_conf_dir}}/server.properties" src=server.properties.j2 force="yes"
  notify:
    - restart kafka

- name: Setup log4j
  template: dest="{{kafka_conf_dir}}/log4j.properties" src=log4j.properties.j2 force="yes"
  notify:
    - restart kafka
