---
- name: setup group
  group: name=kafka system=yes

- name: setup user
  user: name=kafka group=kafka system=yes

- name: fetch binary package
  get_url:
    url: http://apache.mirrors.tds.net/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
    dest: /opt/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz

- name: install binary package
  unarchive: src=/opt/kafka_{{kafka_scala_version}}-{{kafka_version}}.tgz creates=/opt/kafka_{{kafka_scala_version}}-{{kafka_version}} dest=/opt copy=no

- name: create symlink to installation directory
  file: path=/opt/kafka src=/opt/kafka_{{kafka_scala_version}}-{{kafka_version}} state=link

- name: create symlink to conf directory
  file: path={{kafka_conf_dir}} src=/opt/kafka/config state=link

- name: create data directory
  file: path={{kafka_data_dir}} state=directory owner=kafka group=kafka mode=755

- name: create log directory
  file: path={{kafka_log_dir}} state=directory owner=kafka group=kafka mode=755

- name: setup server.properties
  template: dest="{{kafka_conf_dir}}/server.properties" src=server.properties.j2 force="yes"
  notify:
    - restart kafka

- name: setup log4j
  template: dest="{{kafka_conf_dir}}/log4j.properties" src=log4j.properties.j2 force="yes"
  notify:
    - restart kafka
